[package]
name = "rust-multilayer-perceptron"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
itertools = "0.13.0"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
num = "0.4.3"
rand = "0.8.5"
